### ISSUE TITLE
Annotate feature extension roadmap

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1911]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

If anyone has any ideas on what extensions you might want for the `Annotate` feature [main PR here](https://github.com/MarkBind/markbind/pull/1858), feel free to edit / reply to this thread so I can add it in the todos list.

Features that can be extended:
- [ ] Hiding/showing all annotations with a button
- [ ] Annotation Arrow
- [x] Annotation with different shapes

Features to be improved: 
- [ ] Relative size of points
- [ ] Different Legend positioning e.g. inside the image, beside the image etc.

### Describe the solution you'd like

n/a

**Comment by yucheng11122017** [comment]
Hi! I was thinking of modifying `<a-point>` such that different shapes can be used for annotation. 
So far my thoughts is to add a slot so that users can use their own shapes if they want. 

For example, a user can do this: 
```
<annotate src="../../images/annotateSampleImage.png" width="500" alt="Sample Image">
  <!-- Minimal Point -->
  <a-point x="25%" y="25%" content="This point is 25% from the left and 25% from the top">
    <span class="badge bg-primary">Primary</span>
  </a-point>
</annotate>
```
to achieve something like this. 
![image](https://github.com/MarkBind/markbind/assets/77204346/fddcf926-c368-44d4-b77d-b9e5bf65ff25)


If no shape is used, the default button is used (to prevent any breaking changes) 
However, things like size, color and opacity (which is currently used to control the size of the a-point) would no longer work when users use a slot. Instead, they would have to control these things using CSS.

**Comment by kaixin-hc** [comment]
@damithc From a user perspective, which of these sounds useful to you? If these do not currently have a usecase, we can close this issue for now until annotation becomes more widely used

**Comment by damithc** [comment]
@kaixin-hc I am not a heavy user of this feature. So, we can close them for now, until a use case emerges.
