### ISSUE TITLE
Vue hydration issues caused by invalid HTML make page unscrollable after clicking on modal

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2025]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2008

### Tell us about your environment

n/a

### MarkBind version

4.0.1

### What did you do? Describe the bug

--

### Steps to reproduce

Go to https://nus-tic2002-ay2223s1.github.io/website/schedule/week5/topics.html#W5-5c
Click on the following modal link:
![image](https://user-images.githubusercontent.com/1673303/187154313-af744853-4e21-4e22-a74d-6deb0978a6e1.png)

### Expected behavior
Page should work normally.

### Actual behavior

![image](https://user-images.githubusercontent.com/1673303/187154469-a2f530ae-0ff8-4af1-add3-8d2f1fd1c130.png)

The modal doesn't have an `X` for closing, and the scrollbar of the parent page disappears even after closing the modal.

But no such problem in https://nus-cs2103-ay2223s1.github.io/website/schedule/week5/topics.html#implementation-refactoring-how

### Anything else?

Both sites are slight variations of each other. The first is from the `tic2002` branch while the latter is from the `cs2103` branch of the same repo https://github.com/nus-cs2103/website-base
That said, the rest of the content of the page is very different between the two sites as the two module follows different topic orders. 

## TODO
d.easy
- [ ] make the [docs](https://markbind-master.netlify.app/userguide/troubleshooting) more visible by linking it in the modal section, as this has happened quite often when using modals

d.moderate (explore and implement one or all of the solutions proposed:
See https://github.com/MarkBind/markbind/issues/2025#issuecomment-1236055825

- [ ] Check out how other vue-based tools like vuepress / nuxt does it
- [ ] Implementing some simple rules ourselves (e.g. tables)
- [ ] Bringing in some external binary to validate the outputs

**Comment by yixiann** [comment]
I am facing the same issue at:

https://nus-cs2103-ay2223s1.github.io/website/schedule/week5/topics.html#supplementary-requirements

In the sentence:
A supplementary requirements section can be used to capture requirements that do not fit elsewhere. Typically, this is where most Non-Functional Requirements will be listed.

After clicking
"Non-Functional Requirements"

**Comment by tlylt** [comment]
> I am facing the same issue at:

Thanks @yixiann for the bug report!

Hi @damithc, looks like it could be due to Vue hydration issues caused by invalid HTML. There were a few tables referenced in the problematic pages where the `<table>` does not contain a `<tbody>` (functionally, this is fine and doesn't really do much, but for Vue it needs the HTML semantic to be correct), which seems to distort the functionality of the modal.

This is not a problem for other pages either because they don't contain such tables, or they use tables that are generated from markdown (which we will handle the HTML generation).

The offending tables are e.g.:
![image](https://user-images.githubusercontent.com/41845017/188207322-e94c5d1c-4f04-4ab6-aca6-1c9cb9a22b43.png)
They are typically used for set code block side by side, like:
![image](https://user-images.githubusercontent.com/41845017/188207455-3545b105-3524-4d40-8e37-e4281a731ec5.png)

In SE book itself, I found 13 places of such issues (search for `</table>`), fixing them manually (by appending `<tbody>` and `</tbody>` within `<table>` and the modal starts to work as expected again.

**Comment by damithc** [comment]
@tlylt thanks very much for the investigation and figuring out the solution. Seems to work when I tried it. Will update all `<table>`s lacking the `<tbody>` tag.

**Comment by ang-zeyu** [comment]
Great investigation! @tlylt 

I can't remember where I mentioned it but again we can also consider introducing some build time validation for these common violations:
- Implementing some simple rules ourselves (e.g. tables)
- Bringing in some external binary to validate the outputs
- Checkout how other vue-based tools like vuepress / nuxt does it

**Comment by damithc** [comment]
One more case that is not inside a table.

https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/topics.html

![image](https://user-images.githubusercontent.com/1673303/190551247-c6bd8c3f-98e3-4aa2-ad6a-a27a5c6d96a7.png)

**Comment by jonahtanjz** [comment]
> One more case that is not inside a table.
> 
> https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/topics.html

Looks like on the same page there is 1 more `<table>` without a `<tbody>` leading to hydration issue. Running the site in development mode will show these errors in the console:

![image](https://user-images.githubusercontent.com/47470981/190839791-6f2ffa30-e75f-4c8e-a4ca-9845533453ff.png)

Should be this particular table under https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/topics.html#project-management-project-planning-work-breakdown-structure

![image](https://user-images.githubusercontent.com/47470981/190839803-6e0bb8fe-2b31-4eab-b794-c32d0e7bd399.png)

https://github.com/se-edu/se-book/blob/ba0b92d28e14fda03acddd8d98bcba29be9cbb8e/projectPlanning/workBreakdownStructure/text.md?plain=1#L33

**Comment by damithc** [comment]
> Looks like on the same page there is 1 more `<table>` without a `<thead>` and `<tbody>` leading to hydration issue. Running the site in development mode will show these errors in the console:

Thanks for the investigation @jonahtanjz 💯 
It seems I missed a few `<table>` elements because my regular expression find-and-replace didn't account for the `<table>` element having attributes. Fixed now.

**Comment by WillCWX** [comment]
Is this issue closable? Or is there a more desired fix other than making sure that there are no more invalid html leading to hydration issues and component malfunction? (or are we keeping this issue open to reference to for other similar issues)

**Comment by tlylt** [comment]
> Is this issue closable? Or is there a more desired fix other than making sure that there are no more invalid html leading to hydration issues and component malfunction? (or are we keeping this issue open to reference to for other similar issues)

We already have a troubleshooting section on this issue (not fully explained but included a note on missing tbody) [here](https://markbind-master.netlify.app/userguide/troubleshooting)
- [ ] perhaps can make the Docs more visible by linking it in the modal section, as this has happened quite often when using modals

Will edit the issue to include the TODOs mentioned in https://github.com/MarkBind/markbind/issues/2025#issuecomment-1236055825

**Comment by yiwen101** [comment]
I would like to clarify the concept of hydration.
I am working on adding simple rules to detect invalid html structure. One of the rule is that <p> tag can not have block level element as children, and it detects that (to my surprise) 404.md violates the rule.

In 404.vue...js: <div> as child of <p>
![IMAGE 2024-04-01 16:50:57](https://github.com/MarkBind/markbind/assets/121547057/c1948919-85dd-42b8-82bd-e2417c40de5c)

In 404.html, <p><div> ... </div> </p> get corrected into <div></div><p></p>: 
![IMAGE 2024-04-01 16:50:54](https://github.com/MarkBind/markbind/assets/121547057/f7dc5f44-0910-48c2-acb9-cab6da22555e)

String value of "content" in runtime:
![IMAGE 2024-04-01 16:52:13](https://github.com/MarkBind/markbind/assets/121547057/6e51bd8f-4f7c-4975-93d7-cb5509807700)

However, when I do "markbind serve -d" at /docs, I do not experience/see hydration issue. Why is this the case? 
<img width="1047" alt="Screenshot 2024-04-01 at 16 47 10" src="https://github.com/MarkBind/markbind/assets/121547057/231bf338-0d9a-49c6-8a8e-7124fd8aa0c2">

**Comment by tlylt** [comment]
> I would like to clarify the concept of hydration.
> 
> I am working on adding simple rules to detect invalid html structure. One of the rule is that "<p>" tag can not have block level element as children, and it detects that (to my surprise) 404.md violates the rule.

I am not sure why but I do observe this as well. Seems to suggest that some violations (e.g p contains doc ) are "tolerated" while some violations (e.g missing tbody in table) are always (?) reported. Can verify again https://validator.w3.org to check the syntax


I would suggest doing abit more googling to find out...could be due to how browsers implement the HTML spec as well.

**Comment by yiwen101** [comment]
After some primitive testing, it seems that current browsers are quite robust. All the issues listed below seems would not cause hydration issue (though may still leads to unexpected behaviours): 
<img width="388" alt="Screenshot 2024-04-03 at 16 15 50" src="https://github.com/MarkBind/markbind/assets/121547057/c5443f3b-73ac-4aee-acfd-82f3394923f0">

Missing </tbody> remains the only known violation that (always?) leads to hydration issue.

**Comment by kaixin-hc** [comment]
This should be addressed by yiwen101's PR to make this easier to prevent and fix in the future. Let's close this issue for now unless it resurfances.
