### ISSUE TITLE
CS2103T tP docs migration tracker

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2072]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Documentation, Other

### Is your feature request related to a problem? Please describe.

A tracker issue to note down the progress of this migration

### Describe the solution you'd like
- [x] document differences and pros and cons of using MarkBind vs Jekyll
- [x] check the printed colors of headings for any issues/problems (verify if it is a concern)
- [x] share how markbind features should be used?
- [ ] At the end of migration, we should include a link to the migrated website on our showcase
