### ISSUE TITLE
Combine the syntax cheat sheet and full syntax reference pages

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#2091]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I might be mistaken, these 2 pages look extremely similar in the content they offer.

### Describe the solution you'd like

Look into combining these 2 pages by removing the full syntax reference in favour of the cheat sheet. Perhaps rename this "Syntax Reference" as well.

As the cheat sheet page is longer due to the available short examples, consider adding a page nav for navigability. We can organize the sections further into subsections as well.

Another small unrelated thing we can do here is add some spacing between the heading and code blocks for readability.

**Comment by damithc** [comment]
I agree they contain almost the same content. But the initial presentation is slightly different. I wouldn't mind having multiple versions of content even if the differences are slight, provided each one is optimized for some purpose. Its one of MarkBind's strength's to be able to do so, and if structured properly, shouldn't cause any additional maintenance burden.

That said, I agree the cheat sheet can benefit from a page navigation menu.

Plus, the current cheat sheet has things it's not meant to have e.g.,
![image](https://user-images.githubusercontent.com/1673303/212541811-7866c0ce-3bbd-4ca2-99e4-1d0ae957733d.png)
There shouldn't be explanations in here as the cheat sheet is meant for a seasoned user who just want to quickly verify the exact syntax.
Another one that doesn't follow the rest:
![image](https://user-images.githubusercontent.com/1673303/212541957-74a2aa8c-2cb1-4609-ba91-53ee4afd78d8.png)

**Comment by ang-zeyu** [comment]
> But the initial presentation is slightly different.

yes, would the page navigation menu be sufficient to make up for navigability?

>  shouldn't cause any additional maintenance burden.

Imo it's not about maintainence burden, that's not really an issue, but reducing the number of unnecessary sections to make the docs less intimidating to the reader.

> Plus, the current cheat sheet has things it's not meant to have e.g.,

aha.. ok. I expanded a few panels only but both of their expanded contents looked the exact same so I was wondering what's the purpose of having two.

> There shouldn't be explanations in here as the cheat sheet is meant for a seasoned user who just want to quickly verify the exact syntax.

I agree. Could you file a follow up as to what the general differences should be? We can close out this.

**Comment by ang-zeyu** [comment]
Actually, however, I still think we can remove the need for a **full syntax reference** page.

How about:

```
Panels

... minimized panel button with title "Summary Reference" ...
... minimized panel button with title "Full Reference"  ...
```

?

**Comment by damithc** [comment]
@ang-zeyu I agree, we can get rid of the _full syntax reference_ page.

To clarify, the cheat sheet serves as a quick reference for users, for example, something they can print and put up near their computer for each reference. If viewing the online version, it is still useful to easily view the syntax they need with a simple page scroll or a Ctrl+F, without having to expand any panels or wade through lot of details.

The expandable panels in there are not strictly part of the cheat sheet but like a 'bonus feature': if the quick glance at the syntax is not enough, they can expand the panel to find the full details of the feature, instead of navigating to another place to find details. 

After removing the _full syntax reference_ page, we can rename the cheat sheet as _Syntax Reference_ and put a note at the top to inform users they can expand the panel to find the details. That way, the page remains clean so that a printed version of it will still look like a legit cheat sheet (compared to having two minimized panels for each feature).

On a related note, we should tweak the code blocks in their to get rid of horizontal scroll bars so that the printed version shows the full code block.

What do you think?

**Comment by ang-zeyu** [comment]
I see, would having a reference of some form to the full syntax  not be a priority?

We can actually hide the panel buttons during print very easily as well:

```
@media only screen {
  .card-container {
    display: none;
  }
}
```

Instead of a full syntax reference button panel, we can consider have a direct link to the page as well. That could be more useful for the reader to backtrack completely where this feature came from. The same idea of hiding the link during print applies.


```
Panels (panel)
... (short code snippet) ...

// Once expanded,
..link to original page..(hidden in print)
..summary reference..
```

**Comment by ang-zeyu** [comment]
> On a related note, we should tweak the code blocks in their to get rid of horizontal scroll bars so that the printed version shows the full code block.

Do we have still have this feature? Iirc, we removed it sometime ago.

**Comment by damithc** [comment]
> I see, would having a reference of some form to the full syntax not be a priority?

The only difference between the current cheat sheet and the current full syntax page is that the cheat sheet shows a TLDR version (i.e., the 'cheat' version) of the syntax just below the heading.

So, we don't lose anything by removing the full syntax page, as the cheat sheet contains everything the full syntax page had, and more.

> We can actually hide the panel buttons during print very easily as well:

While I don't mind having two panels for the TLDR version and the full version, I don't want the reader to have to click on anything to see the TLDR version. Only those who want the full syntax version should need to expand the panel. So, the TLDR version should be expanded by default.

If we use one page for both purposes, I'm not sure it is a good idea to force-hide some parts from printing. The reader *might* want to print contents from the full details panel too.


> Instead of a full syntax reference button panel, we can consider have a direct link to the page as well.

Yup, that's another option but I'm not so keen on direction. Sending the reader to a different location is not the MarkBind way. Instead, we show everything the readers wants while staying in the original context. Plus, by showing it inside the panel, it is clear which exact content is being presented to the reader; if the reader is sent to another location, it's not as clear exactly from what point to what point of the destination page is the relevant part.

**Comment by ang-zeyu** [comment]
> The only difference between the current cheat sheet and the current full syntax page is that the cheat sheet shows a TLDR version (i.e., the 'cheat' version) of the syntax just below the heading.

I agree, as the content is currently.

> While I don't mind having two panels for the TLDR version and the full version, I don't want the reader to have to click on anything to see the TLDR version.

This is still there (see ["short code snippet"](https://github.com/MarkBind/markbind/issues/2091#issuecomment-1383169450)).

> If we use one page for both purposes, I'm not sure it is a good idea to force-hide some parts from printing.

Yes, the css suggestion is for hiding just the buttons, or links (interactive elements), not the content when expanded. What do you think?

> Yup, that's another option but I'm not so keen on that direction. By cross-embedding the relevant content within a panel (which MarkBind can do easily but most other tools can't), there are two advantages:

I don't really have an inclination, but I believe its a matter of reader preference and workflow.

On the other hand, linking to other pages gives 1. original context of where the content came from (e.g. was it under "components"? "formatting contents"?) 2. creates a shorter and much more navigable page when you have multiple full references expanded simultaneously.

We can consider adding both as well.

**Comment by damithc** [comment]
> Yes, the css suggestion is for hiding just the buttons, or links (interactive elements), not the content when expanded. What do you think?

Sounds good.

> We can consider adding both as well.

Yup. In fact, our panels have a way to specify navigate to another page. We can also use the panel heading to specify where the content come from (as in the example below).
![image](https://user-images.githubusercontent.com/1673303/212720594-730b4c98-4750-4548-bcc9-628af741d06b.png)

**Comment by kaixin-hc** [comment]
To summarise this discussion with crosslinks (and also add my own opinion on how this should be implemented in _italics_)

- [ ] Remove the "full syntax reference page" due to 1) duplication with cheat sheet _2) user is more likely to refer via cheatsheet, search function, or original page._
- [ ] Rename "Syntax Cheatsheet" to "Syntax Reference, add a note ["to inform users they can expand the panel to find the details" ](https://github.com/MarkBind/markbind/issues/2091#issuecomment-1383157079)
- [ ] [Add page navigation to the syntax cheatsheet](https://github.com/MarkBind/markbind/issues/2091#issuecomment-1383144907)
- [ ] [Remove additional information that is not cheatsheet like from the TLDR - examples, output](https://github.com/MarkBind/markbind/issues/2091#issuecomment-1383144907)
- [ ] [Add a link to the panel heading that directly links to the page where the content came from](https://github.com/MarkBind/markbind/issues/2091#issuecomment-1384252685)  _(IMO, the "summary reference" should be included, if there is a case where the full reference is much longer then the link in the panel heading is sufficient to direct a user to more information)_
- [ ] _Remove the x button from the panel (unlikely for this to ever be desired, and if you do happen to click it by accident a few times when printing the result looks weird)_

**Comment by kaixin-hc** [comment]
Closing as this was solved by @jingting1412 's PR, thank you!
