### ISSUE TITLE
Migrate components to Vue 2.0

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#266]
- ~~Accordion.vue~~
- [x] Affix.vue - MarkBind/vue-strap#44 (Ported this because this is needed in the docs!)
- ~~Alert.vue~~
- ~~Aside.vue~~
- ~~buttonGroup.vue~~
- ~~Carousel.vue~~
- ~~Checkbox.vue~~
- ~~Datepicker.vue~~
- [x] Dropdown.vue - MarkBind/vue-strap#38
- [x] DynamicPanel.vue - MarkBind/vue-strap#42
- ~~FormGroup.vue~~
- [x] index.js - Issues fixed by other components.
- ~~Input.vue~~
- [x] main.js - No issues with this file
- [x] Modal.vue - MarkBind/vue-strap#49
- [x] Morph.vue - MarkBind/vue-strap#42
- [x] Navbar.vue - MarkBind/vue-strap#43
- ~~Option.vue~~
- [x] Panel.vue - MarkBind/vue-strap#42
- [x] PanelSwitch.vue - MarkBind/vue-strap#42
- [X] Pic.vue - MarkBind/vue-strap#33
- [x] Popover.vue - MarkBind/vue-strap#49
- ~~Progressbar.vue~~
- [x] Question.vue - MarkBind/vue-strap#45
- ~~Radio.vue~~
- [x] Retriever.vue - MarkBind/vue-strap#42
- [x] Searchbar.vue - MarkBind/vue-strap#40
- ~~Select.vue~~
- ~~Slider.vue~~
- ~~Spinner.vue~~
- [x] Tab.vue MarkBind/vue-strap#41
- [x] TabGroup.vue MarkBind/vue-strap#41
- [x] Tabset.vue MarkBind/vue-strap#41
- [x] TipBox.vue - MarkBind/vue-strap#33
- [x] Tooltip.vue - MarkBind/vue-strap#49
- [x] trigger.vue - MarkBind/vue-strap#49
- [x] Typeahead.vue - MarkBind/vue-strap#40

EDIT: The crossed-out items will not be migrated over because we do not currently use them, so they will be deleted.
