### ISSUE TITLE
Migrate components from Bootstrap 3 to Bootstrap 4

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#298]
- [x] Dropdown - MarkBind/vue-strap#54, MarkBind/vue-strap#60
- [x] Navbar - MarkBind/vue-strap#52
- [x] Panel - MarkBind/vue-strap#53, MarkBind/vue-strap#63
- ~~[ ] Pic~~ - Seems to be OK
- [x] Popover - MarkBind/vue-strap#57
- ~~[ ] Question~~ - Seems to be OK after fixing Panel
- [x] Searchbar - MarkBind/vue-strap#55, MarkBind/vue-strap#60
- [x] Tabs - MarkBind/vue-strap#59
- ~~[ ] Tipbox~~ - Already works
- [x] Tooltip - MarkBind/vue-strap#57
- ~~[ ] Trigger~~ - Should not be affected
- [x] Modal - MarkBind/vue-strap#56
