### ISSUE TITLE
Improve MarkBind's responsive / mobile usability

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [MarkBind/markbind#335]
* **MarkBind Version:** 1.9.0

Table below will be updated as more issues are found.
(Tested in Chrome's responsive mode for iPhone 6/7/8)

Areas of improvement in user guide |
--- |
![responsive-table](https://user-images.githubusercontent.com/31084833/42675822-4837a79c-86a8-11e8-86f5-37e7bafbde27.PNG)<br><h2>1. Tables are not horizontally scroll-able.</h2> |
![responsive-panel-button](https://user-images.githubusercontent.com/31084833/42675848-6086e330-86a8-11e8-865f-289f0c0c7c5d.PNG)<br><h2>2. Panel buttons are misaligned. The button group also takes up too much width, limiting length of the header.</h2> |
![responsive-font](https://user-images.githubusercontent.com/31084833/42675885-7198a5a0-86a8-11e8-9b81-fe8e643ac38b.PNG)<br><h2>3. Font size for headers need better scaling<br>(H4 currently too large).</h2> |
![responsive-image](https://user-images.githubusercontent.com/31084833/42675924-96592860-86a8-11e8-922a-06abbda26f84.PNG)<br><h2>4. Large images are cut off, should have scaled down in size<br> or have it scroll-able.</h2> |
![responsive-popover](https://user-images.githubusercontent.com/31084833/42676562-3c02745e-86ab-11e8-80f0-b4af7948e095.PNG)<br><h2>5. Popover with image is cut off</h2> |
![responsive-footer](https://user-images.githubusercontent.com/31084833/42675962-bb5f7178-86a8-11e8-9fe9-da9cb386812c.PNG)<br><h2>6. Format our footer so it looks good on mobile.</h2> |
![responsive-minimised-btn](https://user-images.githubusercontent.com/31084833/42803881-e95b5ce8-89d9-11e8-8f80-4d3b0d3cfd02.PNG)<br><h2>7. Minimised button text does not wrap when overflowed.</h2> |
<h2>8. Site navigation bar on small devices (576px width or smaller) takes up too much space, we should hide it. User can still access it by "Request for desktop site" on their mobile browsers.</h2>

**Fix status**
- [x] Area 1 - #349
- [x] Area 2 - MarkBind/vue-strap#75
- [x] Area 3 - #350
- [x] Area 4 - MarkBind/vue-strap#76 and #354 
- [x] Area 5 - #357
- [x] Area 6 - #356 (Improves it so it doesn't wrap on resolutions higher than 360x640)
- [x] Area 7 - MarkBind/vue-strap#79
- [x] Area 8 - #356
